#!/bin/bash
# Returns the IP address of a running KVM guest VM
# Assumes a working KVM/libvirt environment
#
# Install:
#   Add this bash function to your ~/.bashrc and `source ~/.bashrc`.
# Usage: 
#   $ virt-ipaddr --all
#   $ virt-ipaddr --hosts (to display like /etc/hosts)
# Credits : Vincent Freret <vfreret@redhat.com>
#
HKVM=`hostname`
virt-addr() {
    VM="$1"
    arp -an | grep "`virsh dumpxml $VM | grep "mac address" | sed "s/.*'\(.*\)'.*/\1/g"`" | awk '{ gsub(/[\(\)]/,"",$2); print $2 }'
    
}

if [ "$1" == "--all" ]; then 
	for i in `virsh list |grep "running" |awk {'print $2'}`;
	do
		IPADDR=`virt-addr $i`
		MACADDR=`virsh dumpxml $i | grep "mac address" | sed "s/.*'\(.*\)'.*/\1/g"`
		echo "$i	[$MACADDR]	 $IPADDR"
	done

fi


if [ "$1" == "--hosts" ]; then 
	for i in `virsh list |grep "running" |awk {'print $2'}`;
	do
		IPADDR=`virt-addr $i`
		MACADDR=`virsh dumpxml $i | grep "mac address" | sed "s/.*'\(.*\)'.*/\1/g"`
		echo "$IPADDR	$i # [$MACADDR] $IPADDR (host:$HKVM)"
	done

fi

